name: coroutines
description: Unity-style coroutines for Dart, allowing resumable function execution.
version: 0.1.0

license: MPL-2.0
homepage: https://github.com/kerberjg/dart_coroutines
repository: https://github.com/kerberjg/dart_coroutines
issue_tracker: https://github.com/kerberjg/dart_coroutines/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
