name: flame_with_coroutines
description: "Example of using dart_coroutines with Flame"
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.9.0
  flutter: ">=3.32.0"

dependencies:
  coroutines:
    path: ../../
  flame: 1.32.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: 1.4.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
