name: "[base] Dart"

on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: '.'

jobs:
  install:
    name: "install"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

  format:
    name: "format"
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: "Get dependencies"
        run: dart pub get
        working-directory: ${{ inputs.path }}

      - name: "dart format"
        run: |
          echo "Checking Dart formatting...\nFiles displayed below:"
          dart format -o none --set-exit-if-changed ./**/*.dart
          echo "No formatting issues found."
        working-directory: ${{ inputs.path }}

  analyze:
    name: "analyze"
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: "Get dependencies"
        run: dart pub get
        working-directory: ${{ inputs.path }}

      - name: Run analysis
        run: dart analyze --fatal-warnings
        working-directory: ${{ inputs.path }}

  test:
    name: "test"
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: "Get dependencies"
        run: dart pub get
        working-directory: ${{ inputs.path }}

      - name: Run tests
        run: dart test --reporter=expanded test/*.dart
        working-directory: ${{ inputs.path }}
