name: "Dart"

on:
  pull_request:
  push:
    branches:
      - main
      - 'release/**'
    paths:
      - '**.dart'
      - './*.yaml'
      - .github/workflows/dart.yaml
      - .github/actions/flutter-setup/**
  release:
    types: [published]


jobs:
  install:
    name: "install"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

  format:
    name: "format"
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: "Get dependencies"
        run: dart pub get

      - name: "dart format"
        run: |
          echo "Checking Dart formatting...\nFiles displayed below:"
          dart format -o none --set-exit-if-changed ./**/*.dart
          echo "No formatting issues found."

  analyze:
    name: "analyze"
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: "Get dependencies"
        run: dart pub get

      - name: Run analysis
        run: dart analyze --fatal-warnings

  test:
    name: "test"
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: "Get dependencies"
        run: dart pub get

      - name: Run tests
        run: dart test --reporter=expanded test/*.dart

  publish:
    name: "publish"
    runs-on: ubuntu-latest
    needs: [format, analyze, test]
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v5
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: "Get dependencies"
        run: dart pub get

      - name: Publish to pub.dev
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
        run: dart pub publish --force