name: "examples"

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'release/**'
    paths:
      - 'examples/**/*.dart'
      - 'examples/**/*.yaml'
      - .github/workflows/examples.yaml
  release:
    types: [published]

jobs:
  dart:
    strategy:
      matrix:
        example: [ base ]
    name: "${{ matrix.example }}"
    uses: ./.github/workflows/_base-dart.yaml
    with:
      path: "examples/${{ matrix.example }}"